theme: jekyll-theme-cayman


<!DOCTYPE html>
<html lang="en">
   <head>
      <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1">
      <title>Home</title>
   
      <link href="css/bootstrap.min.css" rel="stylesheet">
  
    <link rel="stylesheet" href="css/style.css">

</head>
<body>

    
     
<!--Navebar-->

<!--fixedup= that fix navabar upwards--> 
<!--bg light=for add light background-->



<nav class="navbar navbar-expand-lg navbar-light bg-light fixed-top">

    <div class="container">
        <a class="navbar-brand" href="Home.html">Hello Gamers</a>

 <!-- for use with our collapse plugin and other navigation toggling behaviors-->

        <button class="navbar-toggler" type="button" data-toggle="collapse"   
        data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" 
        aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
            


        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="Home.html">Home 
                        <span class="sr-only">(current)</span>
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="play.html">Play</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="About.html">About</a>
                </li>
            </ul>
        </div>
    </div>
</nav>
</body>
</html>
